apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: innovatemart-cluster-secret-store
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      # Using IRSA via the External Secrets Operator service account; no static auth needed