name: Kubernetes Deploy

on:
  push:
    branches:
      - main
      - sandbox
    paths:
      - 'innovatemart-project-bedrock/k8s/**'
      - 'innovatemart-project-bedrock/scripts/**'
      - '.github/workflows/k8s-deploy.yml'

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.33.0"

      - name: Generate kubeconfig
        run: |
          chmod +x innovatemart-project-bedrock/terraform/scripts/generate-kubeconfig.sh
          innovatemart-project-bedrock/terraform/scripts/generate-kubeconfig.sh

      - name: Deploy to Kubernetes
        run: |
          chmod +x innovatemart-project-bedrock/scripts/deploy-app.sh
          innovatemart-project-bedrock/scripts/deploy-app.sh